### ISSUE TITLE
rollapp module can't burn tokens though has permissions

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1518]
trace from UI:

error SIMULATE_TX_FAILED dymension_1405-1 Error: Query failed with (6): rpc error: code = Unknown desc = recovered: module account rollapp does not have permissions to burn tokens: unauthorized [cosmos/cosmos-sdk@v0.47.13/x/bank/keeper/keeper.go:446]
stack:
goroutine 3976272 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
[github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3({0x32c5ac0](http://github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3(%7B0x32c5ac0), 0xc14e7e3240})
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:71](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:71) +0x25
[github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5({0x32c5ac0](http://github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5(%7B0x32c5ac0)?, 0xc14e7e3240?})
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:39](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:39) +0x2d
[github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x32c5ac0](http://github.com/cosmos/cosmos-sdk/baseapp.processRecovery(%7B0x32c5ac0), 0xc14e7e3240}, 0x15?)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:28](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:28) +0x2f
[github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x32c5ac0](http://github.com/cosmos/cosmos-sdk/baseapp.processRecovery(%7B0x32c5ac0), 0xc14e7e3240}, 0x69?)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:33](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:33) +0x53
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1())
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:646](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:646) +0x138
panic({0x32c5ac0?, 0xc14e7e3240?})
	runtime/panic.go:770 +0x132
[github.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.BurnCoins({{{{0x59c3fb0](http://github.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.BurnCoins(%7B%7B%7B%7B0x59c3fb0), 0xc000112040}, {0x59780f8, 0xc000081760}, {0x59c8750, 0xc0014cd270}}, {0x59c3fb0, 0xc000112040}, {0x59c8750, 0xc0014cd270}, ...}, ...}, ...)
	[github.com/cosmos/cosmos-sdk@v0.47.13/x/bank/keeper/keeper.go:446](http://github.com/cosmos/cosmos-sdk@v0.47.13/x/bank/keeper/keeper.go:446) +0x6c5
[github.com/dymensionxyz/dymension/v3/x/rollapp/keeper.msgServer.AddApp({0xc150d99008?}](http://github.com/dymensionxyz/dymension/v3/x/rollapp/keeper.msgServer.AddApp(%7B0xc150d99008?}), {0x59a4cf0?, 0xc1337ba7e0?}, 0xc14e7f0c40)
	[github.com/dymensionxyz/dymension/v3/x/rollapp/keeper/msg_server_app.go:29](http://github.com/dymensionxyz/dymension/v3/x/rollapp/keeper/msg_server_app.go:29) +0x33d
[github.com/dymensionxyz/dymension/v3/x/rollapp/types._Msg_AddApp_Handler.func1({0x59a4cf0](http://github.com/dymensionxyz/dymension/v3/x/rollapp/types._Msg_AddApp_Handler.func1(%7B0x59a4cf0)?, 0xc1337ba7e0?}, {0x358d980?, 0xc14e7f0c40?})
	[github.com/dymensionxyz/dymension/v3/x/rollapp/types/tx.pb.go:1337](http://github.com/dymensionxyz/dymension/v3/x/rollapp/types/tx.pb.go:1337) +0xcb
[github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x59a47e8](http://github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1(%7B0x59a47e8), 0xc14e7ea848}, {0xc150d990d8?, 0x412dc5?}, 0x2a0?, 0xc14e5598c0)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/msg_service_router.go:118](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/msg_service_router.go:118) +0x8a
[github.com/dymensionxyz/dymension/v3/x/rollapp/types._Msg_AddApp_Handler({0x36025e0](http://github.com/dymensionxyz/dymension/v3/x/rollapp/types._Msg_AddApp_Handler(%7B0x36025e0), 0xc0000b0980}, {0x59a47e8, 0xc14e7ea848}, 0x5264ec8, 0xc14e7e2b40)
	[github.com/dymensionxyz/dymension/v3/x/rollapp/types/tx.pb.go:1339](http://github.com/dymensionxyz/dymension/v3/x/rollapp/types/tx.pb.go:1339) +0x143
[github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x59a4698](http://github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2(%7B%7B0x59a4698), 0x7aa71c0}, {0x59c3df0, 0xc14e7bdb80}, {{0xb, 0x0}, {0xc13fd070e0, 0x10}, 0x3f3f4e, {0x2c9e1889, ...}, ...}, ...}, ...)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/msg_service_router.go:139](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/msg_service_router.go:139) +0x2a7
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_), {{0x59a4698, 0x7aa71c0}, {0x59c3df0, 0xc14e7bdb80}, {{0xb, 0x0}, {0xc13fd070e0, 0x10}, 0x3f3f4e, ...}, ...}, ...)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:812](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:812) +0x285
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0008b25a0](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0008b25a0), 0x2, {0xc14e51f600, 0x200, 0x200})
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:755](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/baseapp.go:755) +0xfc5
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...))
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/test_helpers.go:25](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/test_helpers.go:25)
[github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0](http://github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate(%7B%7B%7B0x0), 0x0, 0x0}, {0x59c60e0, 0xc000680000}, 0x0, {0xc001243a50, 0x10}, {0x59dd720, 0xc000112040}, ...}, ...}, ...)
	[github.com/cosmos/cosmos-sdk@v0.47.13/x/auth/tx/service.go:132](http://github.com/cosmos/cosmos-sdk@v0.47.13/x/auth/tx/service.go:132) +0x12f
[github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x346ea00](http://github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler(%7B0x346ea00), 0xc0008b32c0}, {0x59a47e8, 0xc140c0bb88}, 0xc14e51aa00, 0x0)
	[github.com/cosmos/cosmos-sdk@v0.47.13/types/tx/service.pb.go:1416](http://github.com/cosmos/cosmos-sdk@v0.47.13/types/tx/service.pb.go:1416) +0x1a6
[github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x59a4698](http://github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1(%7B%7B0x59a4698), 0x7aa71c0}, {0x59c3df0, 0xc14e7bda00}, {{0xb, 0x0}, {0xc13fd070e0, 0x10}, 0x3f3f4e, {0x2c9e1889, ...}, ...}, ...}, ...)
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/grpcrouter.go:82](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/grpcrouter.go:82) +0x184
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc0008b25a0](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc0008b25a0), 0xc00748e000, {{0xc14e54db00, 0x203, 0x480}, {0xc14e562450, 0x23}, 0x3f3f4e, 0x0})
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/abci.go:698](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/abci.go:698) +0x1a5
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0008b25a0](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0008b25a0), {{0xc14e54db00, 0x203, 0x480}, {0xc14e562450, 0x23}, 0x3f3f4e, 0x0})
	[github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/abci.go:545](http://github.com/cosmos/cosmos-sdk@v0.47.13/baseapp/abci.go:545) +0x776
[github.com/cometbft/cometbft/abci/client.(*localClient).QuerySync(0xc003438f60](http://github.com/cometbft/cometbft/abci/client.(*localClient).QuerySync(0xc003438f60), {{0xc14e54db00, 0x203, 0x480}, {0xc14e562450, 0x23}, 0x0, 0x0})
	[github.com/cometbft/cometbft@v0.37.5/abci/client/local_client.go:259](http://github.com/cometbft/cometbft@v0.37.5/abci/client/local_client.go:259) +0x163
[github.com/cometbft/cometbft/proxy.(*appConnQuery).QuerySync(0xc0070e64b0](http://github.com/cometbft/cometbft/proxy.(*appConnQuery).QuerySync(0xc0070e64b0), {{0xc14e54db00, 0x203, 0x480}, {0xc14e562450, 0x23}, 0x0, 0x0})
	[github.com/cometbft/cometbft@v0.37.5/proxy/app_conn.go:193](http://github.com/cometbft/cometbft@v0.37.5/proxy/app_conn.go:193) +0x1ca
[github.com/cometbft/cometbft/rpc/core.ABCIQuery(0xc0007e0d80](http://github.com/cometbft/cometbft/rpc/core.ABCIQuery(0xc0007e0d80)?, {0xc14e562450?, 0x4?}, {0xc14e54db00?, 0x2?, 0x2?}, 0x0?, 0x93?)
	[github.com/cometbft/cometbft@v0.37.5/rpc/core/abci.go:20](http://github.com/cometbft/cometbft@v0.37.5/rpc/core/abci.go:20) +0x9a
reflect.Value.call({0x3184b40?, 0x5266660?, 0x35fd040?}, {0x3614793, 0x4}, {0xc140c59200, 0x5, 0x5?})
	reflect/value.go:596 +0xca6
reflect.Value.Call({0x3184b40?, 0x5266660?, 0x44c?}, {0xc140c59200?, 0x35fd040?, 0x495ea5?})
	reflect/value.go:380 +0xb9
[github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3({0x5988200](http://github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3(%7B0x5988200), 0xc14e558708}, 0xc140db6fc0)
	[github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:108](http://github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:108) +0xce6
[github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4({0x5988200](http://github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4(%7B0x5988200)?, 0xc14e558708?}, 0xc14e5623c0?)
	[github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:140](http://github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:140) +0x42
net/http.HandlerFunc.ServeHTTP(0xc00190e8f0?, {0x5988200?, 0xc14e558708?}, 0x415abb?)
	net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xc000f2c3c0?, {0x5988200, 0xc14e558708}, 0xc140db6fc0)
	net/http/server.go:2683 +0x1ad
[github.com/cometbft/cometbft/node.(*Node).startRPC.(*Cors).Handler.func9({0x5988200](http://github.com/cometbft/cometbft/node.(*Node).startRPC.(*Cors).Handler.func9(%7B0x5988200), 0xc14e558708}, 0xc140db6fc0)
	[github.com/rs/cors@v1.9.0/cors.go:236](http://github.com/rs/cors@v1.9.0/cors.go:236) +0x184
net/http.HandlerFunc.ServeHTTP(0x0?, {0x5988200?, 0xc14e558708?}, 0xc0c70c69e0?)
	net/http/server.go:2166 +0x29
[github.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x5967d00](http://github.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP(%7B%7B0x5967d00)?, 0xc0006901a0?}, 0xd?}, {0x5988200, 0xc14e558708}, 0xc140db6fc0)
	[github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:256](http://github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:256) +0xfb
[github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x597ea40](http://github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1(%7B0x597ea40), 0xc140daaa80}, 0xc140db6fc0)
	[github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:229](http://github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:229) +0x26c
net/http.HandlerFunc.ServeHTTP(0x415e65?, {0x597ea40?, 0xc140daaa80?}, 0xc140daaa01?)
	net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0x5978aa0?}, {0x597ea40?, 0xc140daaa80?}, 0x6?)
	net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc140e73440, {0x59a4cf0, 0xc0070ed950})
	net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 153
	net/http/server.go:3285 +0x4b4
: panic [cosmos/cosmos-sdk@v0.47.13/baseapp/recovery.go:69] With gas wanted: ‘18446744073709551615’ and gas used: ‘126933’ : unknown request
    at c.queryAbci (queryclient.ts:645:13)
    at async Object.request (utils.ts:37:7)
    at async Object.simulate (queries.ts:74:9)
    at async Qq.simulate (signingstargateclient.ts:281:13)
    at async Mce (tx-service.ts:64:9)
    at async tx-service.ts:88:17
    at async t (use-tx.ts:105:19)

**Comment by omritoptix** [comment]
closing due to #1519
