### ISSUE TITLE
Comos-relayer panics when handling Hub-Evmos testent IBC connection

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#243]
Running the Cosmos-Relayer `v2.3.0` for the IBC between Evmos testenet and the Hub,
Have a **panic** when handling some IBC transactions

```
Apr 27 08:00:58 ip-172-31-17-38 rly[370053]: ts=2023-04-27T08:00:58.495178Z lvl=error msg="Error sending messages" src_chain_id=evmos_9000-4 dst_chain_id=35-C src_client_id=07-tendermint-85 dst_client_id=07-tendermint-18 error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: Int64() out of bound\nstack:\ngoroutine 2146805049 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1cb0660, 0x2b75ce0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1cb0660?, 0x2b75ce0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1cb0660, 0x2b75ce0}, 0xc06c21efc0?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1cb0660, 0x2b75ce0}, 0x2ba8d60?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:632 +0xfd\npanic({0x1cb0660, 0x2b75ce0})\n\truntime/panic.go:838 +0x207\ngithub.com/cosmos/cosmos-sdk/types.Int.Int64({0xdf9f66?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/types/int.go:162 +0x86\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router/keeper.Keeper.ForwardTransferPacket.func1()\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/keeper/keeper.go:291 +0x5f\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router/keeper.Keeper.ForwardTransferPacket({{0x2b82558, 0xc0027886a0}, {0x2ba7260, 0xc000d686a0}, {{0x2ba7260, 0xc000d686a0}, 0xc000010378, {0x2b82558, 0xc002788600}, {0x2b825a8, ...}, ...}, ...}, ...)\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/keeper/keeper.go:301 +0x1046\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router.AppModule.OnRecvPacket({{}, {{0x2b82558, 0xc0027886a0}, {0x2ba7260, 0xc000d686a0}, {{0x2ba7260, 0xc000d686a0}, 0xc000010378, {0x2b82558, 0xc002788600}, ...}, ...}, ...}, ...)\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/module.go:306 +0xadb\ngithub.com/cosmos/ibc-go/v3/modules/core/keeper.Keeper.RecvPacket({{0x0, 0x0}, {0x2ba7260, 0xc000d686a0}, {{0x2b82558, 0xc002788610}, {0x2ba7260, 0xc000d686a0}, {{0x2ba7260, 0xc000d686a0}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/keeper/msg_server.go:412 +0x955\ngithub.com/cosmos/ibc-go/v3/modules/core/04-channel/types._Msg_RecvPacket_Handler.func1({0x2b9af48, 0xc0950a3410}, {0x1f63600?, 0xc08e599760})\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/04-channel/types/tx.pb.go:1323 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x2b9af48, 0xc0950a33e0}, {0x4c0ca6?, 0x41198b?}, 0x1ff1e60?, 0xc0887df170)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/msg_service_router.go:113 +0xdb\ngithub.com/cosmos/ibc-go/v3/modules/core/04-channel/types._Msg_RecvPacket_Handler({0x1fe6220?, 0xc001272500}, {0x2b9af48, 0xc0950a33e0}, 0x290b518, 0xc0956e7de0)\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/04-channel/types/tx.pb.go:1325 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x2b9aed8, 0xc0000540b8}, {0x2ba8d60, 0xc06b8efc00}, {{0xb, 0x0}, {0xc151e089bc, 0x4}, 0xff2cc, {0x23914e5d, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/msg_service_router.go:126 +0x3d0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x2b9aed8, 0xc0000540b8}, {0x2ba8d60, 0xc06b8efc00}, {{0xb, 0x0}, {0xc151e089bc, 0x4}, 0xff2cc, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:760 +0x5c5\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000e92700, 0x2, {0xc113ab5900, 0x2349, 0x2349})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:717 +0xd0c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(0x414307?, {0xc113ab5900?, 0x1e34be0?, 0x2b7e001?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/test_helpers.go:23 +0x2c\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x2bb0da8, 0xc001180380}, {0xc001278508, 0x4}, {0x2b9f520, 0xc000d686a0}, {0x2bab3c8, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/x/auth/tx/service.go:120 +0x12e\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1ee5440?, 0xc0085fc680}, {0x2b9af48, 0xc062866f00}, 0xc0e3fd01e0, 0x0)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/types/tx/service.pb.go:910 +0x170\ngithub.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x2b9aed8, 0xc0000540b8}, {0x2ba8d60, 0xc06b1df100}, {{0xb, 0x0}, {0xc151e089bc, 0x4}, 0xff2cc, {0x23914e5d, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/grpcrouter.go:85 +0x22d\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000e92700, 0xc0085ee900, {{0xc0f6aca000, 0x234c, 0x4800}, {0xc0d1982030, 0x23}, 0xff2cc, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:583 +0x1cf\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc000e92700, {{0xc0f6aca000, 0x234c, 0x4800}, {0xc0d1982030, 0x23}, 0xff2cc, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:427 +0x77d\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc00059f560, {{0xc0f6aca000, 0x234c, 0x4800}, {0xc0d1982030, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:256 +0x171\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x2?, {{0xc0f6aca000, 0x234c, 0x4800}, {0xc0d1982030, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:159 +0x6e\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0x8?, {0xc0d1982030?, 0xc0001a52c0?}, {0xc0f6aca000?, 0x4?, 0xc016a1ca40?}, 0x2?, 0xb9?)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/core/abci.go:20 +0xa6\nreflect.Value.call({0x1d86180?, 0x290d690?, 0x80?}, {0x2004638, 0x4}, {0xc06bef8600, 0x5, 0x18?})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0x1d86180?, 0x290d690?, 0x46eb?}, {0xc06bef8600, 0x5, 0x5})\n\treflect/value.go:339 +0xbf\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x2b99240, 0xc0a89bc048}, 0xc068ee1500)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:96 +0x1075\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x2b99240?, 0xc0a89bc048?}, 0x0?)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:122 +0x5d\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x2b99240?, 0xc0a89bc048?}, 0x54e2c8?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc0001c9c80?, {0x2b99240, 0xc0a89bc048}, 0xc068ee1500)\n\tnet/http/server.go:2462 +0x149\ngithub.com/rs/cors.(*Cors).Handler.func1({0x2b99240, 0xc0a89bc048}, 0xc068ee1500)\n\tgithub.com/rs/cors@v1.8.2/cors.go:231 +0x1c4\nnet/http.HandlerFunc.ServeHTTP(0x160?, {0x2b99240?, 0xc0a89bc048?}, 0x0?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x2b81280?, 0xc003b9d100?}, 0x414307?}, {0x2b99240?, 0xc0a89bc048}, 0xc068ee1500)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:238 +0x122\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x2b99ba0?, 0xc068c0eee0}, 0xc068ee1500)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:211 +0x37f\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x2b99ba0?, 0xc068c0eee0?}, 0x413fa5?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.serverHandler.ServeHTTP({0x2b83f98?}, {0x2b99ba0, 0xc068c0eee0}, 0xc068ee1500)\n\tnet/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc0ec535180, {0x2b9af48, 0xc00862e840})\n\tnet/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3071 +0x4db\n: panic [cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:69] With gas wanted: '0' and gas used: '287547' : unknown request"
```

**Comment by mtsitrin** [comment]
Tried with relayer `v2.0.0`. 
same error

**Comment by mtsitrin** [comment]
@omritoptix
PR on their repo was merged to main
we use older release v3
we probably should fork the repo and cherry pick this PR
