### ISSUE TITLE
Panic when handling batch from non-active sequencer

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#245]
In case multiple sequencers registered for a rollapp,
we have a panic when sending from non-active sequencer:

```
11:57AM INF Subscribe to query module=rpc query=state_update.rollapp_id='rollapp' remote=127.0.0.1:54820
11:57AM INF WSJSONRPC method=subscribe module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":54820,"Zone":""}
11:57AM ERR recovered (error) panic: sequencer is not active
11:57AM ERR stack trace: goroutine 18834 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
github.com/dymensionxyz/dymension/x/rollapp/keeper.PrintPanicRecoveryError({{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x140042e1200}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, {0x35a31828, ...}, ...}, ...}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/keeper/hooks.go:62 +0x58
github.com/dymensionxyz/dymension/x/rollapp/keeper.panicCatchingHook.func1()
	github.com/dymensionxyz/dymension/x/rollapp/keeper/hooks.go:44 +0x64
panic({0x10638c6e0, 0x14001228900})
	runtime/panic.go:838 +0x204
github.com/dymensionxyz/dymension/x/sequencer/keeper.rollapphook.BeforeUpdateState({{{0x106568bc0, 0x1400122a970}, {0x106546030, 0x14000eee110}, {0x106546030, 0x0}, {{0x106568bc0, 0x1400122a970}, 0x1400012bbc8, {0x106546030, ...}, ...}, ...}}, ...)
	github.com/dymensionxyz/dymension/x/sequencer/keeper/hook_listener.go:43 +0x164
github.com/dymensionxyz/dymension/x/rollapp/types.MultiRollappHooks.BeforeUpdateState(...)
	github.com/dymensionxyz/dymension/x/rollapp/types/hooks.go:29
github.com/dymensionxyz/dymension/x/rollapp/keeper.Keeper.BeforeUpdateStateRecoverable.func1({{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x140042e1800}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, {0x35a31828, ...}, ...}, ...}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/keeper/hooks.go:27 +0xa4
github.com/dymensionxyz/dymension/x/rollapp/keeper.panicCatchingHook({{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x140042e1200}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, {0x35a31828, ...}, ...}, ...}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/keeper/hooks.go:48 +0x128
github.com/dymensionxyz/dymension/x/rollapp/keeper.Keeper.BeforeUpdateStateRecoverable({{0x106568bc0, 0x1400122a970}, {0x106546030, 0x14000eee100}, {0x106546030, 0x0}, {0x106543a18, 0x1400000e2e8}, {{0x106568bc0, 0x1400122a970}, ...}}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/keeper/hooks.go:24 +0x120
github.com/dymensionxyz/dymension/x/rollapp/keeper.msgServer.UpdateState({{{0x106568bc0, 0x1400122a970}, {0x106546030, 0x14000eee100}, {0x106546030, 0x0}, {0x106543a18, 0x1400000e2e8}, {{0x106568bc0, 0x1400122a970}, ...}}}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/keeper/msg_server_update_state.go:27 +0x1f8
github.com/dymensionxyz/dymension/x/rollapp.NewHandler.func1({{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x140042e1200}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, {0x35a31828, ...}, ...}, ...}, ...)
	github.com/dymensionxyz/dymension/x/rollapp/handler.go:24 +0x18c
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x140042e1200}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:775 +0x560
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0x14000f41340, 0x2, {0x1400518e000, 0x11c8, 0x1300})
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:717 +0x85c
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(0x10?, {0x1400518e000?, 0x10eef0701?, 0x10424b198?})
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/test_helpers.go:23 +0x34
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x10656ecf8, 0x1400117f900}, {0x140012afb90, 0xd}, {0x106561600, 0x1400122a970}, {0x10656bc98, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.10/x/auth/tx/service.go:120 +0x108
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x10642cb40?, 0x140011f5520}, {0x10655d308, 0x140042d73b0}, 0x140046e30e0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.45.10/types/tx/service.pb.go:910 +0x174
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x10655d298, 0x1400012c008}, {0x10656a4c0, 0x14000eafac0}, {{0xb, 0x0}, {0x14001224970, 0xd}, 0x189, {0x35a31828, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/grpcrouter.go:85 +0x18c
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0x14000f41340, 0x140011e8f30, {{0x140043db400, 0x11cb, 0x2500}, {0x140012a8e40, 0x23}, 0x189, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:583 +0x104
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0x14000f41340, {{0x140043db400, 0x11cb, 0x2500}, {0x140012a8e40, 0x23}, 0x189, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:427 +0x79c
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0x140006a0900, {{0x140043db400, 0x11cb, 0x2500}, {0x140012a8e40, 0x23}, 0x0, 0x0})
	github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:256 +0x14c
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x1400012ccf0?, {{0x140043db400, 0x11cb, 0x2500}, {0x140012a8e40, 0x23}, 0x0, 0x0})
	github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:159 +0x60
github.com/tendermint/tendermint/rpc/core.ABCIQuery(0x8?, {0x140012a8e40?, 0x140032d8180?}, {0x140043db400?, 0x1400303ab08?, 0x1042e5f5c?}, 0x2?, 0x2?)
	github.com/tendermint/tendermint@v0.34.22/rpc/core/abci.go:20 +0x84
reflect.Value.call({0x1062dfb20?, 0x106537738?, 0x1400303b228?}, {0x105655182, 0x4}, {0x140005b5280, 0x5, 0x104b6f0c4?})
	reflect/value.go:556 +0x5e4
reflect.Value.Call({0x1062dfb20?, 0x106537738?, 0x23e9?}, {0x140005b5280, 0x5, 0x5})
	reflect/value.go:339 +0x98
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x10655b648, 0x140011d52a8}, 0x1400303da00)
	github.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:96 +0xc84
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x10655b648?, 0x140011d52a8?}, 0x107c805b8?)
	github.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:122 +0x74
net/http.HandlerFunc.ServeHTTP(0x0?, {0x10655b648?, 0x140011d52a8?}, 0x104b7202c?)
	net/http/server.go:2084 +0x3c
net/http.(*ServeMux).ServeHTTP(0x14000100000?, {0x10655b648, 0x140011d52a8}, 0x1400303da00)
	net/http/server.go:2462 +0x144
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x1065427f8?, 0x14000eaf900?}, 0x10?}, {0x10655b648?, 0x140011d52a8}, 0x1400303da00)
	github.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:238 +0x134
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x10655bfa8?, 0x14000577260}, 0x1400303da00)
	github.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:211 +0x2bc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x10655bfa8?, 0x14000577260?}, 0x10422fb80?)
	net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x106547958?}, {0x10655bfa8, 0x14000577260}, 0x1400303da00)
	net/http/server.go:2916 +0x3fc
net/http.(*conn).serve(0x1400504e460, {0x10655d308, 0x140005da1e0})
	net/http/server.go:1966 +0x56c
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x450
```

**Comment by mtsitrin** [comment]
@omritoptix Currently, we have `BeforeStateUpdate` hooks, that in case of error `panic()`
Then we have `panicCatchingHook` that catches the panic and transforms it to `error`

I want to refactor the hook to return `error` in the first place
