### ISSUE TITLE
Getting a golang panic on `dymd start`

### ISSUE THREAD

**Issue by fshabashev** [dymensionxyz/dymension#798]
After initialising the rollerapp, as per instruction here:
[](https://docs.dymension.xyz/build/start/initialize)

I was trying to follow the further instruction steps and run `dymd start`. 
however upon running `dymd start` I was getting this error at first:
```10:57AM INF Unlocking keyring
10:57AM INF starting ABCI with Tendermint
10:57AM INF starting node with ABCI Tendermint in-process
10:57AM ERR failed init node error="couldn't read GenesisDoc file: open /Users/username/.dymension/config/genesis.json: no such file or directory"
```

to fix it I copied `genesis.json` into the `/Users/username/.dymension/config/` but now I'm getting goland panic error like this:

```(venv) fedorshabashev@192 dymension % dymd start
11:02AM INF Unlocking keyring
11:02AM INF starting ABCI with Tendermint
11:02AM INF starting node with ABCI Tendermint in-process
11:02AM INF service start impl=multiAppConn module=proxy msg={} server=node
11:02AM INF service start connection=query impl=localClient module=abci-client msg={} server=node
11:02AM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
11:02AM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
11:02AM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
11:02AM INF service start impl=EventBus module=events msg={} server=node
11:02AM INF service start impl=PubSub module=pubsub msg={} server=node
11:02AM INF service start impl=IndexerService module=txindex msg={} server=node
11:02AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=v2.0.0-alpha.3
11:02AM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
11:02AM INF initializing blockchain state from genesis.json
panic: value is nil

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/types.AssertValidValue(...)
	github.com/cosmos/cosmos-sdk@v0.46.15/store/types/validity.go:13
github.com/cosmos/cosmos-sdk/store/gaskv.(*Store).Set(0x1056593c0?, {0x1400108b140?, 0x1?, 0x1?}, {0x0?, 0x95?, 0x95?})
	github.com/cosmos/cosmos-sdk@v0.46.15/store/gaskv/store.go:49 +0x114
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.SetAccount({{0x1040b4a28, 0x14001666480}, {0x1040e8110, 0x140014e85a0}, {{0x1040e8110, 0x140014e85a0}, 0x14000011e50, {0x1040b4a28, 0x14001666500}, {0x1040b4a78, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.15/x/auth/keeper/account.go:82 +0x204
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.InitGenesis({{0x1040b4a28, 0x14001666480}, {0x1040e8110, 0x140014e85a0}, {{0x1040e8110, 0x140014e85a0}, 0x14000011e50, {0x1040b4a28, 0x14001666500}, {0x1040b4a78, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.15/x/auth/keeper/genesis.go:23 +0x200
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x1040b4a28, 0x14001666480}, {0x1040e8110, 0x140014e85a0}, {{0x1040e8110, 0x140014e85a0}, 0x14000011e50, {0x1040b4a28, 0x14001666500}, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.15/x/auth/module.go:144 +0xf8
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x1040d4f68, 0x14000054070}, {0x1040e8ab0, 0x140012121c0}, {{0x0, 0x0}, {0x140015c0340, 0xf}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.15/types/module/module.go:322 +0x284
github.com/dymensionxyz/dymension/app.(*App).InitChainer(_, {{0x1040d4f68, 0x14000054070}, {0x1040e8ab0, 0x140012121c0}, {{0x0, 0x0}, {0x140015c0340, 0xf}, 0x0, ...}, ...}, ...)
	github.com/dymensionxyz/dymension/app/app.go:930 +0x1d0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x140010ec380, {{0x2282abc8, 0xedda06dc4, 0x0}, {0x140015c0340, 0xf}, 0x14000ca5440, {0x10590ac88, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.46.15/baseapp/abci.go:71 +0x30c
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x1400125ede0, {{0x2282abc8, 0xedda06dc4, 0x0}, {0x140015c0340, 0xf}, 0x14000ca5440, {0x10590ac88, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.29/abci/client/local_client.go:272 +0x18c
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x140010de330?, {{0x2282abc8, 0xedda06dc4, 0x0}, {0x140015c0340, 0xf}, 0x14000ca5440, {0x10590ac88, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.29/proxy/app_conn.go:77 +0x80
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x102e35c0e, 0x7}}, {0x140015c0340, 0xf}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.29/consensus/replay.go:319 +0xbe0
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x14000530ea0, {0x1040eb188, 0x1400127c820})
	github.com/tendermint/tendermint@v0.34.29/consensus/replay.go:268 +0x388
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x102e35c0e, 0x7}}, {0x140015c0340, 0xf}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.29/node/node.go:329 +0x11c
github.com/tendermint/tendermint/node.NewNode(0x140014ff900, {0x1040cfc00, 0x14001258780}, 0x1400167ab40, {0x1040ac220, 0x1400000f518}, 0x1040abc80?, 0x14000de5860?, 0x1400167ad60, {0x1040d6580, ...}, ...)
	github.com/tendermint/tendermint@v0.34.29/node/node.go:779 +0x3f0
github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x1040f8be0, 0x14000dfadb0}, 0x0, {0x0, 0x0}, {0x1040ef938, ...}, ...}, ...)
	github.com/evmos/ethermint@v0.22.0/server/start.go:374 +0xbd8
github.com/evmos/ethermint/server.StartCmd.func2(0x1400004cc00?, {0x10590ac88?, 0x0?, 0x0?})
	github.com/evmos/ethermint@v0.22.0/server/start.go:158 +0x1ac
github.com/spf13/cobra.(*Command).execute(0x1400004cc00, {0x10590ac88, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x7e4
github.com/spf13/cobra.(*Command).ExecuteC(0x140017efb00)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x380
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x102e2d3d0?, {0x0, 0x0}, {0x14000ec7240, 0x20})
	github.com/cosmos/cosmos-sdk@v0.46.15/server/cmd/execute.go:36 +0x1a8
main.main()
	github.com/dymensionxyz/dymension/cmd/dymd/main.go:15 +0x38
```

**Comment by mtsitrin** [comment]
seems like a genesis issue.
reopen if the problem persists
